### ISSUE TITLE
not mov movdqu

### ISSUE THREAD

**Issue by mgaudet** [jrmuizel/rr-dataflow#4]
_(Preface: rr-dataflow is awesome 👍 )_ 

Seems to have trouble parsing this code: 

    movdqu 0x10(%ebx,%eax,1),%xmm1

Which I get this from: 

    0xf7b7bdcb in ?? () from /lib32/libc.so.6
    >>> origin
    0x1000:	movdqu	xmm1, xmmword ptr [rbx + rax + 0x10]
    not move movdqu
    3
    Traceback (most recent call last):
      File "~/rr-dataflow/flow.py", line 162, in invoke
      File "~/rr-dataflow/flow.py", line 105, in eval_mem_operand
    NameError: name 'src' is not defined
    Error occurred in Python command: name 'src' is not defined
    >>> 
    
Could be worth noting this is a 32-bit binary, built on Ubuntu 17.10

**Comment by jrmuizel** [comment]
I'll take a look. It shouldn't be too hard to fix.

**Comment by jrmuizel** [comment]
I pushed a local change that I had forgot to push upstream. It might fix it.

**Comment by jrmuizel** [comment]
Also, I don't think I've tried using it on 32-bit binaries so watch out for bad results.
